### ISSUE TITLE
Move priority and numberOfArguments under a different namespace

### ISSUE THREAD

**Issue by widoz** [widoz/hooks-interfaces#4]
The WordPress implementation of Hooks need to define 4 elements: **Name**, **Callback**, **Priority** and **Number of Arguments** the callback can get passed.

There's no reason why other system should implements the same concept, may be other systems just need a **name** and a **callback**.

For this reason I want to move **priority** and **callback** out of this package and create a new interface within wp-hooks which will extends the one defined in this package.

**Comment by szepeviktor** [comment]
What a high level of abstraction!

**Comment by widoz** [comment]
At the end I splitted all of the concerns into separated interfaces because a system may only need to have a callback and encapsulate all of the logic within a service which could set just callbacks.

Could be higher and probably over engineered but this part of the hook package is the interface which will be used outside of WordPress and should be higher interoperable.
